<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>firstLineMatch</key>
	<string>^\s*(=-)+\s*$</string>
	<key>name</key>
	<string>ISC Binding log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*((=-)+)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.text.bindinglog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>header</string>
			<key>end</key>
			<string>^\s*((=-)+)\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.text.bindinglog</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.text.bindinglog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.text.bindinglog</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.text.bindinglog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>key-value pair</string>
					<key>match</key>
					<string>^\s*([A-Za-z ]+)(:)(.*?)$</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>other values</string>
					<key>match</key>
					<string>^(.*)$</string>
					<key>name</key>
					<string>constant.numeric.text.bindinglog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.text.bindinglog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Raw Data Offset, with no data (.NET GTW)</string>
			<key>match</key>
			<string>^\s*([0-9A-F]{4}:)\s*$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([0-9A-F]{4}:\s)?((\s{0,3}[0-9A-F]{1,3})+)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.text.bindinglog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.text.bindinglog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Raw Data line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>foo</string>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>comment.line.text.bindinglog</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>foo</string>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.quoted.text.bindinglog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(Sent|Received)(:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.text.bindinglog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Sent/Received Line</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#timestamp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attr</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(&gt;&gt;|&lt;&lt;)\s*([A-Za-z_ ]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.text.bindinglog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Message metadata</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#timestamp</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>storage.type.text.bindinglog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.text.bindinglog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.text.bindinglog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>msgId</string>
			<key>match</key>
			<string>^\s*(msgId)(:)\s(\d+)\s*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.text.bindinglog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((Server|Client)\s(Header|Message))(:)\s*$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(&lt;&lt;&gt;&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#key-value-pair</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(--&gt;|&lt;--)\s*([A-Za-z]+)(:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.text.bindinglog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.text.bindinglog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.text.bindinglog</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((?i)Returning)\s([0-9\-]+(,\s[0-9\-]+)*)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#timestamp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#odbc-key-value-pair</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\*\*\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.bindinglog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>sql</string>
			<key>end</key>
			<string>(\*\*\*)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.text.bindinglog</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#key-value-pair</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#odbc-key-value-pair2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#timestamp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attr</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attr</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.text.bindinglog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.text.bindinglog</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.text.bindinglog</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Za-z ]+)\s*(=)\s*([A-Za-z0-9-]+)</string>
				</dict>
			</array>
		</dict>
		<key>key-value-pair</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.text.bindinglog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.text.bindinglog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Za-z_ ]+)\s*(:)\s*([A-Za-z0-9:\\\./\(\)'", ]+)</string>
		</dict>
		<key>odbc-key-value-pair</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.text.bindinglog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.text.bindinglog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Za-z_ ]+)\s*(=)\s*([A-Za-z0-9\-,]*)</string>
		</dict>
		<key>odbc-key-value-pair2</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.text.bindinglog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.text.bindinglog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([A-Za-z_ ]+)\s*(=)\s*(.*?)\s*$</string>
		</dict>
		<key>timestamp</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\d</string>
					<key>name</key>
					<string>storage.type.text.bindinglog</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>keyword.operator.text.bindinglog</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.bindinglog</string>
	<key>uuid</key>
	<string>3ffb065b-8538-4167-b773-ae0a4ae9455f</string>
</dict>
</plist>
