<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>csplog</string>
	</array>
	<key>firstLineMatch</key>
	<string>^&gt;&gt;&gt; Time:</string>
	<key>name</key>
	<string>CSPLog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^&gt;(?=&gt;&gt;)</string>
			<key>comment</key>
			<string>message block</string>
			<key>end</key>
			<string>(?&lt;=^&gt;&gt;&gt;)</string>
			<key>name</key>
			<string>keyword.operator.csplog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\s+Backtrace) \((.*?)\) (\:) (.*?)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.csplog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.csplog</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.type.csplog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>backtrace</string>
					<key>end</key>
					<string>(?=&gt;&gt;&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.csplog</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.name.csplog</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>support.type.csplog</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>string.quoted.csplog</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>string.quoted.csplog</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^(\s*(/.*/)(.*?))\((.*?)\+([A-Za-z0-9]+)\)\s\[([A-Za-z0-9]+)\]$</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G&gt;&gt;</string>
					<key>comment</key>
					<string>header line</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.csplog</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.csplog</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>header value</string>
							<key>match</key>
							<string>([\sA-Za-z\-]+):\s*([^;]+)(;|$)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s*HTTP\s(Request|Response|Headers)\s*$)</string>
					<key>comment</key>
					<string>HTTP Request or Response (EV9R)</string>
					<key>end</key>
					<string>^(?=&gt;&gt;&gt;)</string>
					<key>name</key>
					<string>support.function.csplog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#request-headers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#response-headers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#unmatched</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(Request Buffer Header)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.csplog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Request Buffer Header</string>
					<key>end</key>
					<string>^(?=&gt;&gt;&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#buffer-headers</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>value</string>
							<key>match</key>
							<string>^.*?$</string>
							<key>name</key>
							<string>string.quoted.csplog</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#unmatched</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(Response Buffer Header)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.csplog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Response Buffer Header</string>
					<key>end</key>
					<string>^(?=&gt;&gt;&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>^\s*CacheSP</string>
							<key>name</key>
							<string>support.function.csplog</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#buffer-headers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#response-headers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#unmatched</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(Request Header)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.csplog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Request Header</string>
					<key>end</key>
					<string>^(?=&gt;&gt;&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.csplog</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.csplog</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^\s*\^([A-Za-z])([0-9]+)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*((Cache Footers)\s*$)|((Cache Headers) (\(([0-9]+)\))?)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.csplog</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.function.csplog</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.quoted.csplog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Misc Headers and Footers</string>
					<key>end</key>
					<string>^(?=&gt;&gt;&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>^\s*CacheSP</string>
							<key>name</key>
							<string>support.function.csplog</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#buffer-headers</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(.*)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.csplog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Default - make a guess</string>
					<key>end</key>
					<string>(?=&gt;&gt;&gt;)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#response-headers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#request-headers</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>buffer-checksum</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.csplog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.csplog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.csplog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.csplog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Fa-f0-9]+):([A-Fa-f0-9]+):([A-Fa-f0-9]+):([A-Fa-f0-9]+)</string>
		</dict>
		<key>buffer-header</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.csplog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.csplog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.csplog</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Za-z]+)\s*(=)\s*([A-Za-z0-9_]+)\s*(\([A-Za-z_]+\))?\s*</string>
		</dict>
		<key>buffer-headers</key>
		<dict>
			<key>begin</key>
			<string>\G:</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#buffer-header</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#buffer-checksum</string>
				</dict>
			</array>
		</dict>
		<key>http-headers</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.csplog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.csplog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>request/response headers</string>
			<key>match</key>
			<string>^\s*([A-Z-a-z\-_]+):\s*(.*?)$</string>
		</dict>
		<key>request-headers</key>
		<dict>
			<key>begin</key>
			<string>^\s*([A-Za-z]+)\s([A-Za-z0-9/%\-\.]+)\s(HTTP)(/)(\d\.\d)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.csplog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.csplog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.csplog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.csplog</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.function.csplog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>HTTP verb line</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#http-headers</string>
				</dict>
			</array>
		</dict>
		<key>response-headers</key>
		<dict>
			<key>begin</key>
			<string>^\s*(HTTP)(/)(\d\.\d)\s([0-9]{3})\s([A-Za-z\ ]+)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.csplog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.csplog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.csplog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.csplog</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.language.csplog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>HTTP Response line</string>
			<key>end</key>
			<string>^\s*$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#http-headers</string>
				</dict>
			</array>
		</dict>
		<key>unmatched</key>
		<dict>
			<key>match</key>
			<string>^.*?$</string>
			<key>name</key>
			<string>comment.line.csplog</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.csplog</string>
	<key>uuid</key>
	<string>a955f7a4-a116-4876-bdcf-9d76e89da8b6</string>
</dict>
</plist>
