<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>isclog</string>
	</array>
	<key>firstLineMatch</key>
	<string>^\^\%ISCLOG</string>
	<key>name</key>
	<string>ISCLOG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.isclog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.isclog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.isclog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>log level</string>
			<key>match</key>
			<string>^(\^\%ISCLOG)\s*(=)\s*(([0-9])|\".*?\")\s*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.isclog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.isclog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.isclog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>data counter</string>
			<key>match</key>
			<string>^(\^\%ISCLOG\(\"Data\"\))\s*(=)\s*([0-9]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.isclog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.isclog</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.isclog</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.isclog</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.isclog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Filter</string>
			<key>match</key>
			<string>^(\^\%ISCLOG\((\"(Category|Job|Tag|ErrorDetail)\")(,(\"?.*?\"?))?\))\s*(=)\s*([0-9]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.isclog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.isclog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.isclog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.isclog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>MaxLogEntries filter</string>
			<key>match</key>
			<string>^(\^\%ISCLOG\((\"MaxLogEntries\")\))\s*(=)\s*([0-9]+)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\^\%ISCLOG\(\"Data\"\s*,\s*[0-9]+\s*\))(=)(\$(?i)lb)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.isclog</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.isclog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.isclog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>new entry</string>
			<key>end</key>
			<string>(?&lt;=\))$</string>
			<key>name</key>
			<string>comment.line.isclog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.isclog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>level 1 (log level)</string>
					<key>end</key>
					<string>(?=\)$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[^\,]*(?=\,)</string>
							<key>name</key>
							<string>variable.language.isclog</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\,</string>
							<key>comment</key>
							<string>level 2 (function)</string>
							<key>end</key>
							<string>(?=\)$)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>[^\,]*(?=\,)</string>
									<key>name</key>
									<string>constant.numeric.isclog</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>\,</string>
									<key>comment</key>
									<string>level 3 (message)</string>
									<key>end</key>
									<string>(?=\)$)</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>captures</key>
											<dict>
												<key>2</key>
												<dict>
													<key>name</key>
													<string>entity.name</string>
												</dict>
												<key>3</key>
												<dict>
													<key>name</key>
													<string>support.function.isclog</string>
												</dict>
												<key>4</key>
												<dict>
													<key>name</key>
													<string>constant.numeric.isclog</string>
												</dict>
											</dict>
											<key>match</key>
											<string>((\"(\[.*?\])?.*?\")|(\$c\(.*?\)))*</string>
											<key>name</key>
											<string>entity.name.isclog</string>
										</dict>
										<dict>
											<key>begin</key>
											<string>\,</string>
											<key>comment</key>
											<string>level 4 (PID)</string>
											<key>end</key>
											<string>(?=\)$)</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>match</key>
													<string>[^\,]*(?=\,)</string>
													<key>name</key>
													<string>keyword.control.isclog</string>
												</dict>
												<dict>
													<key>begin</key>
													<string>\,</string>
													<key>comment</key>
													<string>level 5 (namespace)</string>
													<key>end</key>
													<string>(?=\)$)</string>
													<key>patterns</key>
													<array>
														<dict>
															<key>match</key>
															<string>[^\,]*(?=\,)</string>
															<key>name</key>
															<string>variable.language.isclog</string>
														</dict>
														<dict>
															<key>begin</key>
															<string>\,</string>
															<key>comment</key>
															<string>level 6 (timestamp)</string>
															<key>end</key>
															<string>(?=\)$)</string>
															<key>patterns</key>
															<array>
																<dict>
																	<key>match</key>
																	<string>[^\,]*(?=\,)</string>
																	<key>name</key>
																	<string>storage.modifier.isclog</string>
																</dict>
																<dict>
																	<key>begin</key>
																	<string>\,</string>
																	<key>comment</key>
																	<string>level 7 routine</string>
																	<key>end</key>
																	<string>(?=\)$)</string>
																	<key>patterns</key>
																	<array>
																		<dict>
																			<key>match</key>
																			<string>[^\,]*(?=\,)</string>
																			<key>name</key>
																			<string>string.quoted.double.isclog</string>
																		</dict>
																		<dict>
																			<key>begin</key>
																			<string>\,</string>
																			<key>comment</key>
																			<string>level 8 (requestId)</string>
																			<key>end</key>
																			<string>(?=\)$)</string>
																			<key>patterns</key>
																			<array>
																				<dict>
																					<key>match</key>
																					<string>[^\,]*(?=\,)</string>
																					<key>name</key>
																					<string>support.class.isclog</string>
																				</dict>
																				<dict>
																					<key>begin</key>
																					<string>\,</string>
																					<key>comment</key>
																					<string>level 9 (sessionId)</string>
																					<key>end</key>
																					<string>(?=\)$)</string>
																					<key>patterns</key>
																					<array>
																						<dict>
																							<key>match</key>
																							<string>[^\)]*(?=\))</string>
																							<key>name</key>
																							<string>support.function.isclog</string>
																						</dict>
																					</array>
																				</dict>
																			</array>
																		</dict>
																	</array>
																</dict>
															</array>
														</dict>
													</array>
												</dict>
											</array>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\^\%ISCLOG\(\"Data\"\s*,\s*[0-9]+\s*\,\s*0(\,(.*?))?\))\s*(=)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.isclog</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.language.isclog</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.isclog</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>data entry</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>string.quoted.double.isclog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.isclog</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.line.isclog</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.language.isclog</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\"|^)(.*?)(=)(.*)\"</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.isclog</string>
	<key>uuid</key>
	<string>853c4505-d59e-4e5c-8999-a5d709e779e2</string>
</dict>
</plist>
